# CI Workflow

name: CI - Build

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - 'extern/**'
      - 'tools/**'
      - '.vscode/**'
      - '.editorconfig'
      - '.gitignore'
      - '.mbed'
      - 'LICENSE'
      - 'README.md'

  pull_request:
    branches:
      - develop
    paths-ignore:
      - 'docs/**'
      - 'extern/**'
      - 'tools/**'
      - '.vscode/**'
      - '.editorconfig'
      - '.gitignore'
      - '.mbed'
      - 'LICENSE'
      - 'README.md'

jobs:

  make_config_make_all:
    name: Config & Build LekaOS
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Cache Mbed OS
        id: cache-mbed-os
        uses: actions/cache@v2
        with:
          path: ./extern/mbed-os
          key: ${{ runner.os }}-${{ hashFiles('./extern/mbed-os/.git/ORIG_HEAD') }}

      - name: Clone Mbed OS
        if: steps.cache-mbed-os.outputs.cache-hit != 'true'
        run: |
          make clone_mbed BRANCH=mbed-os-6.3.0

      - name: Cache CMake Config
        id: cache-cmake-config
        uses: actions/cache@v2
        with:
          path: ./cmake/config
          key: ${{ runner.os }}-${{ hashFiles('./cmake/config/**.h') }}

      - name: Config build system
        if: steps.cache-cmake-config.outputs.cache-hit != 'true'
        run: |
          make config

      - name: Cache build output
        id: cache-build-output
        uses: actions/cache@v2
        with:
          path: ./build
          key: ${{ runner.os }}-${{ hashFiles('./build/.ninja_deps') }}

      - name: Build LekaOS & al.
        run: |
          make
