# CI Workflow

name: CI - LekaOS & al.

on:
  push:
    branches:
      - develop
      - master

  pull_request:
    branches:
      - develop
      - "feature/**"
      - "bugfix/**"

jobs:
  config_build:
    name: Config & Build
    runs-on: [self-hosted, build]
    strategy:
      fail-fast: false
      matrix:
        custom_target: ["LEKA_V1_1_DEV", "LEKA_V1_2_DEV"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Create cache variables
        id: create_cache_variables
        run: |
          echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"
          echo "::set-output name=runner_name::$(basename $(dirname $(dirname $(dirname $(pwd)))))"

      - name: Cache ccache files
        id: cache_ccache_files
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${ { runner.os } }-cache-ccache_files-${ { steps.create_cache_variables.outputs.timestamp } }
          restore-keys: |
            ${ { runner.os } }-cache-ccache_files-

      - name: Cache Mbed OS
        id: cache_mbed_os
        uses: actions/cache@v2
        with:
          path: extern/mbed-os
          key: ${{ runner.os }}-cache-mbed_os-${{ hashFiles('extern/mbed-os/platform/include/platform/mbed_version.h', '.mbed_version') }}

      - name: Curl Mbed OS
        if: steps.cache_mbed_os.outputs.cache-hit != 'true'
        run: |
          make mbed_curl

      - name: Cache cmake config & build directory
        id: cache_cmake_config_and_build_directory
        uses: actions/cache@v2
        with:
          path: |
            _build/${{ matrix.custom_target }}
            _build/cmake_config/${{ matrix.custom_target }}
          key: ${{ runner.os }}-${{ steps.create_cache_variables.outputs.runner_name }}-cache-cmake_config_and_build_directory-${{ matrix.custom_target }}-${{ hashFiles('mbed_app.json', 'targets/custom_targets.json', '.mbed_version', 'Makefile', 'CMakeLists.txt') }}

      - name: Config build system
        if: steps.cache_cmake_config_and_build_directory.outputs.cache-hit != 'true'
        run: |
          make clean_config TARGET_BOARD=${{ matrix.custom_target }}

      - name: Ccache pre build
        run: |
          make ccache_prebuild

      - name: Build LekaOS & al.
        run: |
          make TARGET_BOARD=${{ matrix.custom_target }}

      - name: Ccache post build
        run: |
          make ccache_postbuild

      - name: Upload compile_commands.json to gist
        if: ${{ matrix.custom_target == 'LEKA_V1_2_DEV' }}
        uses: exuanbo/actions-deploy-gist@v1.0.3
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 705c060b5fa6bf84eda2e172c1db2aec
          gist_file_name: compile_commands.json
          file_path: _build/${{ matrix.custom_target }}/compile_commands.json
