# CI - Check Workflow

name: CI - Check

on: push

jobs:
  check_clang_format:
    name: Clang Format
    runs-on: [self-hosted, check]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Run clang-format
        run: |
          python3 tools/run-clang-format.py -r --extension=h,c,cpp --color=always --style=file ./src ./drivers ./libs ./spikes ./tests
