# CI - Check Workflow

name: CI - Check

on:
  push:
    paths:
      - '**.h'
      - '**.c'
      - '**.cpp'

jobs:

  check_clang_format:
    name: Clang Format
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Clone Mbed OS
        run: |
          python3 tools/run-clang-format.py -r --extension=h,c,cpp --color=always --style=file ./src ./drivers ./libs ./spikes ./tests
