# CI Workflow

name: Config & Build

on:
  push:
    branches:
      - develop
      - master

  pull_request:
    branches:
      - develop
      - "feature/**"
      - "bugfix/**"

jobs:
  leka_os_and_al:
    name: LekaOS & al.
    runs-on: ubuntu-latest
    container:
      image: weareleka/docker-arm-toolchain:latest
      env:
        CCACHE_DIR: /ccache
      options: -v ccache:/ccache

    strategy:
      fail-fast: false
      matrix:
        custom_target: ["LEKA_V1_2_DEV"]
    steps:
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(date +%s)"
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Cache ccache
        id: cache_cccache
        uses: actions/cache@v2
        with:
          path: /ccache
          key: ${{ runner.os }}-${{ matrix.custom_target }}-cache-cccache-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.custom_target }}-cache-cccache-

      - name: Cache Mbed OS
        id: cache_mbed_os
        uses: actions/cache@v2
        with:
          path: extern/mbed-os
          key: ${{ runner.os }}-cache-mbed_os-${{ hashFiles('extern/mbed-os/platform/include/platform/mbed_version.h', '.mbed_version') }}

      - name: Curl Mbed OS
        if: steps.cache_mbed_os.outputs.cache-hit != 'true'
        run: |
          make mbed_curl

      - name: Config build system
        run: |
          make config TARGET_BOARD=${{ matrix.custom_target }}

      - name: Ccache pre build
        run: |
          make ccache_prebuild

      - name: Build LekaOS & al.
        run: |
          make TARGET_BOARD=${{ matrix.custom_target }}

      - name: Ccache post build
        run: |
          make ccache_postbuild

      - name: Upload build artifacts
        if: |
          contains(matrix.custom_target, 'LEKA_V1_2_DEV') &&
          (contains(github.ref, 'develop') || contains(github.ref, 'master'))
        uses: actions/upload-artifact@v2
        with:
          name: LEKA_V1_2_DEV-Build-Artifacts
          retention-days: 7
          path: |
            _build/LEKA_V1_2_DEV/**/*.bin
            _build/LEKA_V1_2_DEV/**/*.hex
            _build/LEKA_V1_2_DEV/**/*.elf
