# CI - Check Workflow

name: Linters

on: push

jobs:
  clang_format:
    name: clang-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install clang-format 13
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
          sudo apt update -y
          sudo apt install -y --no-install-recommends clang-format-13
          clang-format-13 --version

      - name: Run clang-format
        run: |
          python3 tools/run-clang-format.py --clang-format-executable=clang-format-13 -r --extension=h,hpp,c,cpp --color=always --style=file ./app ./drivers ./libs ./spikes ./tests
