# CMake CI Workflow

name: CI

on: [push]

jobs:

  make_config_make_all:
    name: Config & Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Test script
        run: |
          brew install coreutils
          export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
          brew install ninja
          brew tap ArmMbed/homebrew-formulae
          brew install arm-none-eabi-gcc
          make clone_mbed BRANCH=mbed-os-6.3.0
          python3 -m pip install -U --user mbed-cli pyserial intelhex prettytable
          python3 -m pip install -U --user -r lib/_vendor/mbed-os/requirements.txt
          make config
          make

  clang_format_check:
    name: Clang Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.10
        with:
          source: './src ./lib ./spike ./test'
          exclude: './lib/_vendor'
          extensions: 'h,cpp,c'
          clangFormatVersion: 10
          inplace: "" # meaning false, see https://github.com/DoozyX/clang-format-lint-action/issues/18#issue-710169130
